title                    : "Helen Kesting"
title_separator          : "-"

description              : "Geospatial Analyst and Landscape Ecologist"
email: helenkesting@gmail.com

theme: minima
skin: dark


